title: spiroth
email: spir.0th.xyz@gmail.com
description: "I develop programs, produce music, and make videos."
baseurl: "" 
url: "https://spiroth.github.io"

# SEO settings
author:
  name: Gian Borcillo
  url: https://spiroth.github.io
twitter:
  username: spir0th
  card: summary

# Theme settings
logo: /assets/img/logo.png
show_navigation: true
show_socials: true
color-scheme: auto-default-dark

# Front matter settings
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: default
  -
    scope:
      path: "_posts"
      type: posts
    values:
      excerpt_separator: <!-- more -->
      permalink: /blogs/:title:output_ext
      comments: true
      layout: post

# Build settings
remote_theme: godalming123/minimal
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
